### ISSUE TITLE
Kube.nvim feature request

### ISSUE THREAD

**Issue by mimparat132** [mimparat132/kube.nvim#1]
- Add the ability to configure your notify agent.
- Don't have the plugin write the file or figure out some way to prevent neovim from thinking the file has changes that need to be saved before exiting the file after running the search functions.
- Add the ability to decrypt base64 values in k8s secrets and copy them to the buffer.

**Comment by mimparat132** [comment]
- When inside a k8s manifest that you want to patch, it would be nice to be able to copy the following to the clipboard with a keybinding:
```yaml
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2beta1
      kind: HelmRelease
      name: ingress-nginx
```
